### ISSUE TITLE
THANK YOU!! 

### ISSUE THREAD

**Issue by maxjendrall** [Youssefbenhammouda/openai-ratelimiter#1]
Hi Youseff, just wanted to give a quick thank-you!

No solution I tried so far actually worked as expected... thought I'd have to implement this myself haha.

Thank you for saving so much time.

**Comment by Youssefbenhammouda** [comment]
Hi toorusr,
I am very happy that the repository saved some time.
Feel free to contribute to the project.
Thanks.
