### ISSUE TITLE
Limited redis connection possibilities

### ISSUE THREAD

**Issue by ZinoKader** [Youssefbenhammouda/openai-ratelimiter#7]
First of all, thank you for open sourcing this!

I am a bit sceptical about limiting the user to pass in a `redis_host` and `redis_port`.
It does not allow for using a different database than `/0`, or supplying a password, for instance.

If one could pass in a [redis connection string](https://redis-py.readthedocs.io/en/stable/#redis.from_url), that would in itself open up for more possibilities for the redis connection, otherwise, mirroring its args in the constructor is another option.

**Comment by Youssefbenhammouda** [comment]
Hi, thanks for your suggestion.
It's been a while since I checked on this project.
I will keep this in mind when I am updating the repo.
Also, You are welcome if you want to make a pull request.
